#services:
#  mysql:
#    image: mysql:8.0
#    container_name: sbqs-mysql
#    environment:
#      MYSQL_DATABASE: sbqs
#      MYSQL_ROOT_PASSWORD: sqlpass
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  redis:
#    image: redis:7
#    container_name: sbqs-redis
#    ports:
#      - "6379:6379"
#
#volumes:
#  mysql_data:

services:
  redis:
    image: redis:7
    container_name: sbqs-redis
    ports:
      - "6379:6379"
